#!/bin/bash

BRANCH_NAME=$(git symbolic-ref --short HEAD | sed 's/[^0-9]*//g')
BRANCH_NAME="${BRANCH_NAME##*/}"

BRANCH_IN_COMMIT=$(grep -c "\[$BRANCH_NAME\]" $1)

sed -i.bak -e "1s/^/():\n\nissue: #$BRANCH_NAME \n\# Types: refactor,fix,feat,doc,chore,build,test/" $1
